### ISSUE TITLE
Using keyword arguments pollutes code_typed

### ISSUE THREAD

**Issue by chriselrod** [SciML/Static.jl#7]
```julia
julia> using Static, ArrayInterface
[ Info: Precompiling Static [aedffcd0-7271-4cad-89d0-dc628f76c6d3]
[ Info: Precompiling ArrayInterface [4fba245c-0d91-5ea0-9b3e-6abc04ee57a9]

julia> A = rand(3,4);

julia> @code_typed ArrayInterface.offsets(A)
CodeInfo(
1 ── %1 = Base.sle_int(1, 1)::Bool
└───      goto #3 if not %1
2 ── %3 = Base.sle_int(1, 0)::Bool
└───      goto #4
3 ──      nothing::Nothing
4 ┄─ %6 = φ (#2 => %3, #3 => false)::Bool
└───      goto #6 if not %6
5 ──      invoke Base.getindex(()::Tuple, 1::Int64)::Union{}
└───      unreachable
6 ──      goto #7
7 ──      goto #8
8 ──      goto #9
9 ──      goto #10
10 ─      Base.arraysize(x, 1)::Int64
│         Base.arraysize(x, 2)::Int64
│         Base.arraysize(x, 1)::Int64
│         Base.arraysize(x, 2)::Int64
└───      goto #11
11 ─      return (static(1), static(1))
) => Tuple{StaticInt{1}, StaticInt{1}}
```
If we instead define:
```julia
julia> ArrayInterface.offsets(x) = Static._eachop(offsets, (x,), nstatic(Val(ndims(x))))

julia> @code_typed ArrayInterface.offsets(A)
CodeInfo(
1 ─     Base.arraysize(x, 1)::Int64
│       Base.arraysize(x, 2)::Int64
│       Base.arraysize(x, 1)::Int64
│       Base.arraysize(x, 2)::Int64
└──     return (static(1), static(1))
) => Tuple{StaticInt{1}, StaticInt{1}}
```
The `code_llvm` is identical, but the use of keyword arguments makes typed code more verbose.
The fact that Julia fails to optimize things away (leaving LLVM to do it) also suggests the use of keyword arguments could potentially lead to missed optimizations.

Ideally, the `@code_typed` wouldn't include any `Base.arraysize`s either.

**Comment by Tokazama** [comment]
I think there are two problems here.

1. The keyword argument for `eachop` 
2. The way `Array` stores information for its axes

I think the `arraysize` is coming from forming the `Base.OneTo` that is part of each axis. We can special case `offsets` for `Array` to get around this, but ideally arrays (particularly `DenseArray`s) would just store their size and offsets together as axes instead of having a special field/storage pattern for every bit of information.
